apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace.yaml
  - 02-prometheus.yaml
  - grafana/01-grafana-config.yaml
  - grafana/04-grafana-pod-identity.yaml
  - grafana/03-grafana-config-dashboards.yaml
  - grafana/05-grafana.yaml
  - grafana/dashboards/ngsa-prometheus.yaml
  - grafana/dashboards/ngsa-fluentbit.yaml
  