apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: grafana-id
  namespace: monitoring
spec:
  type: 0
  resourceID: /subscriptions/648dcb5a-de1e-48b2-af6b-fe6ef28d355c/resourcegroups/rg-ngsa-pre-central-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ngsadev-ngsa-id
  clientID: 6555187f-d743-48f9-ab23-1f5b6218ee41
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: grafana-id-binding
  namespace: monitoring
spec:
  azureIdentity: grafana-id
  selector: grafana-id
---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: grafana-aad-auth-secret
  namespace: monitoring
spec:
  provider: azure
  secretObjects:
  - secretName: grafana-aad-client-secret
    type: Opaque
    data:
      - objectName: grafana-aad-client-secret
        key: clientSecret
  parameters:
    usePodIdentity: "true"
    keyvaultName: kv-aks-6jqf6qyt7jarg 
    objects:  |
      array:
        - |
          objectName: grafana-aad-client-secret
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
