---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-log-config
  namespace: fluentbit
data:
  zone: $ASB_CLUSTER_LOCATION
  region: $ASB_CLUSTER_GEO_LOCATION
  lodeLog: loderunner
  ngsaLog: ngsa
