apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini:  |
    [auth]
    disable_login_form = true

    [auth.basic]
    enabled = false

    [auth.azuread]
    name = Azure AD
    enabled = true
    allow_sign_up = true
    client_id = ${ASB_GRAFANA_SP_CLIENT_ID}
    scopes = openid email profile
    auth_url = https://login.microsoftonline.com/${ASB_GRAFANA_SP_TENANT_ID}/oauth2/v2.0/authorize
    token_url = https://login.microsoftonline.com/${ASB_GRAFANA_SP_TENANT_ID}/oauth2/v2.0/token
