apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: $ASB_GRAFANA_MI_NAME
  namespace: monitoring
spec:
  type: 0
  resourceID: ${ASB_NGSA_MI_RESOURCE_ID}
  clientID: ${ASB_NGSA_MI_CLIENT_ID}

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: ${ASB_GRAFANA_MI_NAME}-binding
  namespace: monitoring
spec:
  azureIdentity: $ASB_GRAFANA_MI_NAME
  selector: $ASB_GRAFANA_MI_NAME

---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  provider: azure
  secretObjects:
  - secretName: grafana-aad-client-secret
    type: Opaque
    data:
      - objectName: grafana-aad-client-secret
        key: clientSecret
  - secretName: grafana-azure-monitor-client-secret
    type: Opaque
    data:
      - objectName: grafana-azure-monitor-client-secret
        key: clientSecret
  parameters:
    usePodIdentity: "true"
    keyvaultName: "${ASB_KV_NAME}"
    objects: |
      array:
        - |
          objectName: grafana-aad-client-secret
          objectType: secret
        - |
          objectName: grafana-azure-monitor-client-secret
          objectType: secret
    tenantId: "${ASB_TENANT_ID}"
