apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner-clientmode
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner-clientmode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner-clientmode
  template:
    metadata:
      labels:
        app: loderunner-clientmode
        aadpodidbinding: ngsa-asb-loderunner-id
        deploy: 22-04-14-21-16-44
        version: beta-2204-14-21
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-lr:beta
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          args: 
          - --mode 
          - Client
          - --secrets-volume
          - /app/secrets
          - --prometheus
          - --zone
          - az-westus2-dev
          - --region
          - westus2
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: lr-secrets
      nodeSelector:
        agentpool: npuser01

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-clientmode
  namespace: loderunner
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http 
      protocol: TCP
      name: http
  selector:
    app: loderunner-clientmode
