apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: ngsajrod-ngsa-id
  namespace: ngsa
spec:
  type: 0
  resourceID: /subscriptions/648dcb5a-de1e-48b2-af6b-fe6ef28d355c/resourcegroups/rg-ngsa-jrod-asb/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ngsajrod-ngsa-id
  clientID: 554a1f97-6920-41f1-ad08-ad2c5e5479cb

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: ngsajrod-ngsa-id-binding
  namespace: ngsa
spec:
  azureIdentity: ngsajrod-ngsa-id
  selector: ngsajrod-ngsa-id

---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ngsa-secrets
  namespace: ngsa
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "kv-aks-hov33kygp3nts"
    objects: |
      array:
        - |
          objectName: CosmosDatabase
          objectType: secret
        - |
          objectName: CosmosCollection
          objectType: secret
        - |
          objectName: CosmosKey
          objectType: secret
        - |
          objectName: CosmosUrl
          objectType: secret
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
