apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/bootstrap
  - ../base-dev/bootstrap
  - ../base/fluentbit
  - ../base/istio
  - ../base/ngsa
  - ../base/monitoring
  - dashboards/ngsa-az-blocked-traffic.yaml
  - dashboards/ngsa-az-monitor-perf.yaml
  - dashboards/ngsa-az-monitor-rel.yaml
patchesStrategicMerge:
  - overlays/bootstrap-overlays.yaml
  - overlays/fluentbit-overlays.yaml
  - overlays/istio-overlays.yaml
  - overlays/ngsa-overlays.yaml
