apiVersion: v1
kind: Namespace
metadata:
  name: loderunner
---
apiVersion: v1
kind: Pod

metadata:
  name: loderunner
  namespace: loderunner
  labels:
    app: loderunner

spec:
  restartPolicy: OnFailure
  containers:
  - name: loderunner
    image: ghcr.io/retaildevcrews/ngsa-lr:beta
    imagePullPolicy: Always
    args:
    - -l
    - "100"
    - -r
    - -s
    - http://ngsa-memory.ngsa:8080
    - http://ngsa-cosmos.ngsa:8080
    - -f
    - benchmark.json
    # - --prometheus
    # resources:
    #   limits:
    #     memory: 512Mi
    #     cpu: 500m
    #   requests:
    #     memory: 256Mi
    #     cpu: 250m
