apiVersion: v1
kind: Pod

metadata:
  name: loderunner
  namespace: ngsa-l8r

spec:
  restartPolicy: OnFailure
  containers:
  - name: app
    image: ghcr.io/retaildevcrews/ngsa-lr:beta
    imagePullPolicy: Always
    resources:
      limits:
        memory: "512Mi"
        cpu: "1000m"
      requests: 
        memory: "512Mi"
        cpu: "500m"
    args:
    - -l
    - "100"
    - -r
    - -s
    - http://ngsa-memory.ngsa:8080
    - http://ngsa-cosmos.ngsa:8080
    - http://ngsa-java.ngsa:8080
    - -f
    - benchmark.json
